name: "godot-ci export"
on:
  push:
    branches:
      - release

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: cosmicpiscary
  ITCH_GAME: cosmic-piscary
  ITCH_USER: erebrus

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
    - name: Web Build
      run: |
        mkdir -v -p build/html
        godot -v --headless --export-release "Web" build/html/index.html
        godot -v --headless --export-release "Web" build/html/index.html
    - name: Publish to Itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: web
        PACKAGE: build/html
  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          cd src
          godot -v --headless --export-release "MacOS" ../build/mac/$EXPORT_NAME.zip
          godot -v --headless --export-release "MacOS" ../build/mac/$EXPORT_NAME.zip
      - name: Publish to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: mac
          PACKAGE: build/mac

  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd src
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Publish to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          PACKAGE: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd src
          godot -v --headless --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
          godot -v --headless --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Publish to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          PACKAGE: build/linux